import "./globals.css";
import { Open_Sans } from "next/font/google";
import Navigation from "@/components/Navbar";
import AuthContext from "@/context/AuthContext";

const openSans = Open_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={openSans.className}>
      <body className="w-full max-w-screen-xl overflow-auto mx-auto">
        <AuthContext>
          <header className="sticky top-0 bg-white z-10 border-b">
            <Navigation />
          </header>
          <main className="bg-neutral-50">{children}</main>
        </AuthContext>
      </body>
    </html>
  );
}
